"""Refresh curated API pages from source syntax; --check never writes files.

Edit api_reference.json for scope and explanation. This tool reads the packaged
module list and Python syntax without importing the application or dependencies.
It refuses missing/uncatalogued modules, classes, and selected callables instead
of inventing descriptions. Existing removed-class URLs use explicit replacements.
"""

import argparse
import ast
import json
from pathlib import Path
import sys
import tomllib


ROOT = Path(__file__).resolve().parents[1]
NOTICE = "<!-- Generated by tools/update_api_reference.py from curated api_reference.json and source syntax. -->"


def slug(name):
    return name.replace("_", "-")


def module_page(name):
    return f"API-Module-{slug(name)}.md"


def class_page(name):
    return f"API-Class-{slug(name)}.md"


def source_link(module, node=None):
    fragment = f"#L{node.lineno}" if node else ""
    return f"../src/{module}.py{fragment}"


def call_signature(node):
    prefix = "async def " if isinstance(node, ast.AsyncFunctionDef) else "def "
    result = prefix + node.name + "(" + ast.unparse(node.args) + ")"
    if node.returns:
        result += " -> " + ast.unparse(node.returns)
    return result + ":"


def callable_sections(module, nodes, selected):
    result = []
    for name in selected:
        node = nodes.get(name)
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            raise ValueError(f"Selected callable is missing: {module}.{name}")
        decorators = [ast.unparse(item) for item in node.decorator_list]
        decorators = [item for item in decorators if item in ("classmethod", "staticmethod", "property")]
        signature = "\n".join([*("@" + item for item in decorators), call_signature(node)])
        result += [f"### `{name}`", "", f"[Source]({source_link(module, node)})", "", "```python", signature, "```", ""]
    return result


def generate():
    catalog = json.loads((ROOT / "tools/api_reference.json").read_text(encoding="utf-8"))
    packaging = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    modules = packaging["tool"]["setuptools"]["py-modules"]
    if set(modules) != set(catalog["modules"]):
        raise ValueError("Packaged modules and curated API module inventory differ; update api_reference.json.")
    pages = {}
    class_locations = {}
    index = [NOTICE, "# API Reference", "", "Use this reference to locate code and check selected call signatures. These are application internals, not a promised stable third-party API. Start with the [Developer Guide](Developer-Guide.md) for setup and changes, or [Architecture Overview](Architecture-Overview.md) for data flow.", "", "The module inventory follows `pyproject.toml`. Explanations are curated; declarations and source links are read from the current source without importing Qt. Only selected methods are shown. Private attributes and inherited Qt methods are intentionally omitted.", "", "## Modules", "", "| Module | Responsibility |", "| --- | --- |"]
    for module in modules:
        spec = catalog["modules"][module]
        tree = ast.parse((ROOT / "src" / (module + ".py")).read_text(encoding="utf-8"))
        definitions = {node.name: node for node in tree.body if isinstance(node, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef))}
        classes = {name: node for name, node in definitions.items() if isinstance(node, ast.ClassDef)}
        if set(classes) != set(spec.get("classes", {})):
            raise ValueError(f"Class inventory differs in {module}; update api_reference.json.")
        index += [f"| [`{module}`]({module_page(module)}) | {spec['summary']} |"]
        body = [NOTICE, f"# Module: `{module}`", "", spec["summary"], "", f"[Source]({source_link(module)}) | [API index](API-Reference.md)", "", spec["details"], ""]
        if classes:
            body += ["## Classes", "", "| Class | Role |", "| --- | --- |"]
            for name, node in classes.items():
                if name in class_locations:
                    raise ValueError(f"Duplicate class page name: {name}")
                class_locations[name] = module
                cls_spec = spec["classes"][name]
                body += [f"| [`{name}`]({class_page(name)}) | {cls_spec['summary']} |"]
                cls_body = [NOTICE, f"# Class: `{name}`", "", cls_spec["summary"], "", f"[Module]({module_page(module)}) | [Source]({source_link(module, node)}) | [API index](API-Reference.md)", ""]
                bases = ", ".join(ast.unparse(base) for base in node.bases) or "object"
                cls_body += [f"**Bases:** `{bases}`.", ""]
                if cls_spec.get("details"):
                    cls_body += [cls_spec["details"], ""]
                if any(isinstance(item, ast.Name) and item.id == "dataclass" or isinstance(item, ast.Call) and isinstance(item.func, ast.Name) and item.func.id == "dataclass" for item in node.decorator_list):
                    fields = [item for item in node.body if isinstance(item, ast.AnnAssign)]
                    if fields:
                        cls_body += ["## Declared data fields", "", "```python"]
                        cls_body += [ast.unparse(item) for item in fields]
                        cls_body += ["```", "", "`field(default_factory=list)` creates a separate list for each instance." if any("default_factory=list" in ast.unparse(item) for item in fields) else "These are field declarations; follow the source for validation and conversion.", ""]
                selected = cls_spec.get("methods", [])
                if selected:
                    cls_body += ["## Selected methods", "", "Declarations include `self` or `cls` as written in the source. Qt event handlers follow Qt's calling conventions.", ""]
                    cls_body += callable_sections(module, {item.name: item for item in node.body if isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef))}, selected)
                pages[class_page(name)] = "\n".join(cls_body).rstrip() + "\n"
            body += [""]
        if spec.get("functions"):
            body += ["## Selected functions", ""]
            body += callable_sections(module, definitions, spec["functions"])
        pages[module_page(module)] = "\n".join(body).rstrip() + "\n"
    for name, replacement in catalog.get("replaced_classes", {}).items():
        if name in class_locations:
            raise ValueError(f"A replacement note conflicts with a current class: {name}")
        for target in replacement["targets"]:
            if target not in class_locations:
                raise ValueError(f"Replacement class is missing: {target}")
        links = ", ".join(f"[`{target}`]({class_page(target)})" for target in replacement["targets"])
        pages[class_page(name)] = f"{NOTICE}\n# Former class: `{name}`\n\n{replacement['summary']}\n\nCurrent code: {links}.\n\nThis page preserves the earlier documentation URL. The old class is not defined in the current source.\n"
    index += ["", "## Keeping this reference current", "", "Edit `tools/api_reference.json` when responsibilities or selected entry points change, then run:", "", "```sh", "python tools/update_api_reference.py", "python tools/update_api_reference.py --check", "python tools/wiki_docs.py check", "```", "", "The first command refreshes these API pages; `--check` reports drift without writing. Do not edit generated pages directly. Narrative architecture and developer pages are maintained separately. See [Documentation Guide](Documentation-Guide.md) for wiki publication."]
    pages["API-Reference.md"] = "\n".join(index) + "\n"
    stale = {path.name for path in (ROOT / "wiki").glob("API-*.md")} - set(pages)
    if stale:
        raise ValueError("Unaccounted existing API pages (preserve their URLs): " + ", ".join(sorted(stale)))
    return pages


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Report differences without changing files.")
    args = parser.parse_args()
    try:
        pages = generate()
    except (ValueError, SyntaxError, OSError, KeyError) as exc:
        print(f"API reference error: {exc}", file=sys.stderr)
        return 1
    changed = []
    for name, content in pages.items():
        path = ROOT / "wiki" / name
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            changed.append(name)
            if not args.check:
                path.write_text(content, encoding="utf-8", newline="\n")
    if args.check and changed:
        print("API pages need refresh: " + ", ".join(changed))
        return 1
    print(f"API reference: {len(pages)} pages checked; {len(changed)} refreshed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
